/*
 * REST API
 * The REST API is used for all API interactions with DataCite services.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@datacite.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.datacite.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.datacite.JSON;

/**
 * DoiPropertiesMetadataCreatorsInnerAffiliationInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-04T16:42:13.755252895+02:00[Europe/Prague]")
public class DoiPropertiesMetadataCreatorsInnerAffiliationInner {
  public static final String SERIALIZED_NAME_AFFILIATION_IDENTIFIER = "affiliationIdentifier";
  @SerializedName(SERIALIZED_NAME_AFFILIATION_IDENTIFIER)
  private String affiliationIdentifier;

  public static final String SERIALIZED_NAME_AFFILIATION_IDENTIFIER_SCHEME = "affiliationIdentifierScheme";
  @SerializedName(SERIALIZED_NAME_AFFILIATION_IDENTIFIER_SCHEME)
  private String affiliationIdentifierScheme;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SCHEME_URI = "schemeUri";
  @SerializedName(SERIALIZED_NAME_SCHEME_URI)
  private String schemeUri;

  public DoiPropertiesMetadataCreatorsInnerAffiliationInner() {
  }

  public DoiPropertiesMetadataCreatorsInnerAffiliationInner affiliationIdentifier(String affiliationIdentifier) {
    
    this.affiliationIdentifier = affiliationIdentifier;
    return this;
  }

   /**
   * Get affiliationIdentifier
   * @return affiliationIdentifier
  **/
  @javax.annotation.Nullable

  public String getAffiliationIdentifier() {
    return affiliationIdentifier;
  }


  public void setAffiliationIdentifier(String affiliationIdentifier) {
    this.affiliationIdentifier = affiliationIdentifier;
  }


  public DoiPropertiesMetadataCreatorsInnerAffiliationInner affiliationIdentifierScheme(String affiliationIdentifierScheme) {
    
    this.affiliationIdentifierScheme = affiliationIdentifierScheme;
    return this;
  }

   /**
   * Get affiliationIdentifierScheme
   * @return affiliationIdentifierScheme
  **/
  @javax.annotation.Nullable

  public String getAffiliationIdentifierScheme() {
    return affiliationIdentifierScheme;
  }


  public void setAffiliationIdentifierScheme(String affiliationIdentifierScheme) {
    this.affiliationIdentifierScheme = affiliationIdentifierScheme;
  }


  public DoiPropertiesMetadataCreatorsInnerAffiliationInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public DoiPropertiesMetadataCreatorsInnerAffiliationInner schemeUri(String schemeUri) {
    
    this.schemeUri = schemeUri;
    return this;
  }

   /**
   * Get schemeUri
   * @return schemeUri
  **/
  @javax.annotation.Nullable

  public String getSchemeUri() {
    return schemeUri;
  }


  public void setSchemeUri(String schemeUri) {
    this.schemeUri = schemeUri;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoiPropertiesMetadataCreatorsInnerAffiliationInner doiPropertiesMetadataCreatorsInnerAffiliationInner = (DoiPropertiesMetadataCreatorsInnerAffiliationInner) o;
    return Objects.equals(this.affiliationIdentifier, doiPropertiesMetadataCreatorsInnerAffiliationInner.affiliationIdentifier) &&
        Objects.equals(this.affiliationIdentifierScheme, doiPropertiesMetadataCreatorsInnerAffiliationInner.affiliationIdentifierScheme) &&
        Objects.equals(this.name, doiPropertiesMetadataCreatorsInnerAffiliationInner.name) &&
        Objects.equals(this.schemeUri, doiPropertiesMetadataCreatorsInnerAffiliationInner.schemeUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(affiliationIdentifier, affiliationIdentifierScheme, name, schemeUri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoiPropertiesMetadataCreatorsInnerAffiliationInner {\n");
    sb.append("    affiliationIdentifier: ").append(toIndentedString(affiliationIdentifier)).append("\n");
    sb.append("    affiliationIdentifierScheme: ").append(toIndentedString(affiliationIdentifierScheme)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    schemeUri: ").append(toIndentedString(schemeUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("affiliationIdentifier");
    openapiFields.add("affiliationIdentifierScheme");
    openapiFields.add("name");
    openapiFields.add("schemeUri");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DoiPropertiesMetadataCreatorsInnerAffiliationInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DoiPropertiesMetadataCreatorsInnerAffiliationInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DoiPropertiesMetadataCreatorsInnerAffiliationInner is not found in the empty JSON string", DoiPropertiesMetadataCreatorsInnerAffiliationInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!DoiPropertiesMetadataCreatorsInnerAffiliationInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DoiPropertiesMetadataCreatorsInnerAffiliationInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("affiliationIdentifier") != null && !jsonObj.get("affiliationIdentifier").isJsonNull()) && !jsonObj.get("affiliationIdentifier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `affiliationIdentifier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("affiliationIdentifier").toString()));
      }
      if ((jsonObj.get("affiliationIdentifierScheme") != null && !jsonObj.get("affiliationIdentifierScheme").isJsonNull()) && !jsonObj.get("affiliationIdentifierScheme").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `affiliationIdentifierScheme` to be a primitive type in the JSON string but got `%s`", jsonObj.get("affiliationIdentifierScheme").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("schemeUri") != null && !jsonObj.get("schemeUri").isJsonNull()) && !jsonObj.get("schemeUri").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `schemeUri` to be a primitive type in the JSON string but got `%s`", jsonObj.get("schemeUri").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DoiPropertiesMetadataCreatorsInnerAffiliationInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DoiPropertiesMetadataCreatorsInnerAffiliationInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DoiPropertiesMetadataCreatorsInnerAffiliationInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DoiPropertiesMetadataCreatorsInnerAffiliationInner.class));

       return (TypeAdapter<T>) new TypeAdapter<DoiPropertiesMetadataCreatorsInnerAffiliationInner>() {
           @Override
           public void write(JsonWriter out, DoiPropertiesMetadataCreatorsInnerAffiliationInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DoiPropertiesMetadataCreatorsInnerAffiliationInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DoiPropertiesMetadataCreatorsInnerAffiliationInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DoiPropertiesMetadataCreatorsInnerAffiliationInner
  * @throws IOException if the JSON string is invalid with respect to DoiPropertiesMetadataCreatorsInnerAffiliationInner
  */
  public static DoiPropertiesMetadataCreatorsInnerAffiliationInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DoiPropertiesMetadataCreatorsInnerAffiliationInner.class);
  }

 /**
  * Convert an instance of DoiPropertiesMetadataCreatorsInnerAffiliationInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

