/*
 * REST API
 * The REST API is used for all API interactions with DataCite services.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@datacite.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.datacite.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.datacite.api.model.ContributorType;
import org.datacite.api.model.DoiPropertiesMetadataCreatorsInnerAffiliationInner;
import org.datacite.api.model.DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner;
import org.datacite.api.model.NameType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.datacite.JSON;

/**
 * DoiPropertiesMetadataContributorsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-04T16:42:13.755252895+02:00[Europe/Prague]")
public class DoiPropertiesMetadataContributorsInner {
  public static final String SERIALIZED_NAME_NAME_TYPE = "nameType";
  @SerializedName(SERIALIZED_NAME_NAME_TYPE)
  private NameType nameType;

  public static final String SERIALIZED_NAME_NAME_IDENTIFIERS = "nameIdentifiers";
  @SerializedName(SERIALIZED_NAME_NAME_IDENTIFIERS)
  private List<DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner> nameIdentifiers = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_GIVEN_NAME = "givenName";
  @SerializedName(SERIALIZED_NAME_GIVEN_NAME)
  private String givenName;

  public static final String SERIALIZED_NAME_FAMILY_NAME = "familyName";
  @SerializedName(SERIALIZED_NAME_FAMILY_NAME)
  private String familyName;

  public static final String SERIALIZED_NAME_AFFILIATION = "affiliation";
  @SerializedName(SERIALIZED_NAME_AFFILIATION)
  private List<DoiPropertiesMetadataCreatorsInnerAffiliationInner> affiliation = null;

  public static final String SERIALIZED_NAME_CONTRIBUTOR_TYPE = "contributorType";
  @SerializedName(SERIALIZED_NAME_CONTRIBUTOR_TYPE)
  private ContributorType contributorType;

  public static final String SERIALIZED_NAME_LANG = "lang";
  @SerializedName(SERIALIZED_NAME_LANG)
  private String lang;

  public DoiPropertiesMetadataContributorsInner() {
  }

  public DoiPropertiesMetadataContributorsInner nameType(NameType nameType) {
    
    this.nameType = nameType;
    return this;
  }

   /**
   * Get nameType
   * @return nameType
  **/
  @javax.annotation.Nullable

  public NameType getNameType() {
    return nameType;
  }


  public void setNameType(NameType nameType) {
    this.nameType = nameType;
  }


  public DoiPropertiesMetadataContributorsInner nameIdentifiers(List<DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner> nameIdentifiers) {
    
    this.nameIdentifiers = nameIdentifiers;
    return this;
  }

  public DoiPropertiesMetadataContributorsInner addNameIdentifiersItem(DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner nameIdentifiersItem) {
    if (this.nameIdentifiers == null) {
      this.nameIdentifiers = new ArrayList<>();
    }
    this.nameIdentifiers.add(nameIdentifiersItem);
    return this;
  }

   /**
   * Get nameIdentifiers
   * @return nameIdentifiers
  **/
  @javax.annotation.Nullable

  public List<DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner> getNameIdentifiers() {
    return nameIdentifiers;
  }


  public void setNameIdentifiers(List<DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner> nameIdentifiers) {
    this.nameIdentifiers = nameIdentifiers;
  }


  public DoiPropertiesMetadataContributorsInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public DoiPropertiesMetadataContributorsInner givenName(String givenName) {
    
    this.givenName = givenName;
    return this;
  }

   /**
   * Get givenName
   * @return givenName
  **/
  @javax.annotation.Nullable

  public String getGivenName() {
    return givenName;
  }


  public void setGivenName(String givenName) {
    this.givenName = givenName;
  }


  public DoiPropertiesMetadataContributorsInner familyName(String familyName) {
    
    this.familyName = familyName;
    return this;
  }

   /**
   * Get familyName
   * @return familyName
  **/
  @javax.annotation.Nullable

  public String getFamilyName() {
    return familyName;
  }


  public void setFamilyName(String familyName) {
    this.familyName = familyName;
  }


  public DoiPropertiesMetadataContributorsInner affiliation(List<DoiPropertiesMetadataCreatorsInnerAffiliationInner> affiliation) {
    
    this.affiliation = affiliation;
    return this;
  }

  public DoiPropertiesMetadataContributorsInner addAffiliationItem(DoiPropertiesMetadataCreatorsInnerAffiliationInner affiliationItem) {
    if (this.affiliation == null) {
      this.affiliation = new ArrayList<>();
    }
    this.affiliation.add(affiliationItem);
    return this;
  }

   /**
   * Get affiliation
   * @return affiliation
  **/
  @javax.annotation.Nullable

  public List<DoiPropertiesMetadataCreatorsInnerAffiliationInner> getAffiliation() {
    return affiliation;
  }


  public void setAffiliation(List<DoiPropertiesMetadataCreatorsInnerAffiliationInner> affiliation) {
    this.affiliation = affiliation;
  }


  public DoiPropertiesMetadataContributorsInner contributorType(ContributorType contributorType) {
    
    this.contributorType = contributorType;
    return this;
  }

   /**
   * Get contributorType
   * @return contributorType
  **/
  @javax.annotation.Nullable

  public ContributorType getContributorType() {
    return contributorType;
  }


  public void setContributorType(ContributorType contributorType) {
    this.contributorType = contributorType;
  }


  public DoiPropertiesMetadataContributorsInner lang(String lang) {
    
    this.lang = lang;
    return this;
  }

   /**
   * Get lang
   * @return lang
  **/
  @javax.annotation.Nullable

  public String getLang() {
    return lang;
  }


  public void setLang(String lang) {
    this.lang = lang;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoiPropertiesMetadataContributorsInner doiPropertiesMetadataContributorsInner = (DoiPropertiesMetadataContributorsInner) o;
    return Objects.equals(this.nameType, doiPropertiesMetadataContributorsInner.nameType) &&
        Objects.equals(this.nameIdentifiers, doiPropertiesMetadataContributorsInner.nameIdentifiers) &&
        Objects.equals(this.name, doiPropertiesMetadataContributorsInner.name) &&
        Objects.equals(this.givenName, doiPropertiesMetadataContributorsInner.givenName) &&
        Objects.equals(this.familyName, doiPropertiesMetadataContributorsInner.familyName) &&
        Objects.equals(this.affiliation, doiPropertiesMetadataContributorsInner.affiliation) &&
        Objects.equals(this.contributorType, doiPropertiesMetadataContributorsInner.contributorType) &&
        Objects.equals(this.lang, doiPropertiesMetadataContributorsInner.lang);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nameType, nameIdentifiers, name, givenName, familyName, affiliation, contributorType, lang);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoiPropertiesMetadataContributorsInner {\n");
    sb.append("    nameType: ").append(toIndentedString(nameType)).append("\n");
    sb.append("    nameIdentifiers: ").append(toIndentedString(nameIdentifiers)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    affiliation: ").append(toIndentedString(affiliation)).append("\n");
    sb.append("    contributorType: ").append(toIndentedString(contributorType)).append("\n");
    sb.append("    lang: ").append(toIndentedString(lang)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("nameType");
    openapiFields.add("nameIdentifiers");
    openapiFields.add("name");
    openapiFields.add("givenName");
    openapiFields.add("familyName");
    openapiFields.add("affiliation");
    openapiFields.add("contributorType");
    openapiFields.add("lang");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DoiPropertiesMetadataContributorsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DoiPropertiesMetadataContributorsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DoiPropertiesMetadataContributorsInner is not found in the empty JSON string", DoiPropertiesMetadataContributorsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!DoiPropertiesMetadataContributorsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DoiPropertiesMetadataContributorsInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("nameIdentifiers") != null && !jsonObj.get("nameIdentifiers").isJsonNull()) {
        JsonArray jsonArraynameIdentifiers = jsonObj.getAsJsonArray("nameIdentifiers");
        if (jsonArraynameIdentifiers != null) {
          // ensure the json data is an array
          if (!jsonObj.get("nameIdentifiers").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `nameIdentifiers` to be an array in the JSON string but got `%s`", jsonObj.get("nameIdentifiers").toString()));
          }

          // validate the optional field `nameIdentifiers` (array)
          for (int i = 0; i < jsonArraynameIdentifiers.size(); i++) {
            DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner.validateJsonObject(jsonArraynameIdentifiers.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("givenName") != null && !jsonObj.get("givenName").isJsonNull()) && !jsonObj.get("givenName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `givenName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("givenName").toString()));
      }
      if ((jsonObj.get("familyName") != null && !jsonObj.get("familyName").isJsonNull()) && !jsonObj.get("familyName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `familyName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("familyName").toString()));
      }
      if (jsonObj.get("affiliation") != null && !jsonObj.get("affiliation").isJsonNull()) {
        JsonArray jsonArrayaffiliation = jsonObj.getAsJsonArray("affiliation");
        if (jsonArrayaffiliation != null) {
          // ensure the json data is an array
          if (!jsonObj.get("affiliation").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `affiliation` to be an array in the JSON string but got `%s`", jsonObj.get("affiliation").toString()));
          }

          // validate the optional field `affiliation` (array)
          for (int i = 0; i < jsonArrayaffiliation.size(); i++) {
            DoiPropertiesMetadataCreatorsInnerAffiliationInner.validateJsonObject(jsonArrayaffiliation.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("lang") != null && !jsonObj.get("lang").isJsonNull()) && !jsonObj.get("lang").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lang` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lang").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DoiPropertiesMetadataContributorsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DoiPropertiesMetadataContributorsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DoiPropertiesMetadataContributorsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DoiPropertiesMetadataContributorsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<DoiPropertiesMetadataContributorsInner>() {
           @Override
           public void write(JsonWriter out, DoiPropertiesMetadataContributorsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DoiPropertiesMetadataContributorsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DoiPropertiesMetadataContributorsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DoiPropertiesMetadataContributorsInner
  * @throws IOException if the JSON string is invalid with respect to DoiPropertiesMetadataContributorsInner
  */
  public static DoiPropertiesMetadataContributorsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DoiPropertiesMetadataContributorsInner.class);
  }

 /**
  * Convert an instance of DoiPropertiesMetadataContributorsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

