/*
 * REST API
 * The REST API is used for all API interactions with DataCite services.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@datacite.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.datacite.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.datacite.JSON;

/**
 * DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-04T16:42:13.755252895+02:00[Europe/Prague]")
public class DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner {
  public static final String SERIALIZED_NAME_NAME_IDENTIFIER = "nameIdentifier";
  @SerializedName(SERIALIZED_NAME_NAME_IDENTIFIER)
  private String nameIdentifier;

  public static final String SERIALIZED_NAME_NAME_IDENTIFIER_SCHEME = "nameIdentifierScheme";
  @SerializedName(SERIALIZED_NAME_NAME_IDENTIFIER_SCHEME)
  private String nameIdentifierScheme;

  public static final String SERIALIZED_NAME_SCHEME_URI = "schemeUri";
  @SerializedName(SERIALIZED_NAME_SCHEME_URI)
  private String schemeUri;

  public DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner() {
  }

  public DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner nameIdentifier(String nameIdentifier) {
    
    this.nameIdentifier = nameIdentifier;
    return this;
  }

   /**
   * Get nameIdentifier
   * @return nameIdentifier
  **/
  @javax.annotation.Nullable

  public String getNameIdentifier() {
    return nameIdentifier;
  }


  public void setNameIdentifier(String nameIdentifier) {
    this.nameIdentifier = nameIdentifier;
  }


  public DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner nameIdentifierScheme(String nameIdentifierScheme) {
    
    this.nameIdentifierScheme = nameIdentifierScheme;
    return this;
  }

   /**
   * Get nameIdentifierScheme
   * @return nameIdentifierScheme
  **/
  @javax.annotation.Nullable

  public String getNameIdentifierScheme() {
    return nameIdentifierScheme;
  }


  public void setNameIdentifierScheme(String nameIdentifierScheme) {
    this.nameIdentifierScheme = nameIdentifierScheme;
  }


  public DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner schemeUri(String schemeUri) {
    
    this.schemeUri = schemeUri;
    return this;
  }

   /**
   * Get schemeUri
   * @return schemeUri
  **/
  @javax.annotation.Nullable

  public String getSchemeUri() {
    return schemeUri;
  }


  public void setSchemeUri(String schemeUri) {
    this.schemeUri = schemeUri;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner doiPropertiesMetadataCreatorsInnerNameIdentifiersInner = (DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner) o;
    return Objects.equals(this.nameIdentifier, doiPropertiesMetadataCreatorsInnerNameIdentifiersInner.nameIdentifier) &&
        Objects.equals(this.nameIdentifierScheme, doiPropertiesMetadataCreatorsInnerNameIdentifiersInner.nameIdentifierScheme) &&
        Objects.equals(this.schemeUri, doiPropertiesMetadataCreatorsInnerNameIdentifiersInner.schemeUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nameIdentifier, nameIdentifierScheme, schemeUri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner {\n");
    sb.append("    nameIdentifier: ").append(toIndentedString(nameIdentifier)).append("\n");
    sb.append("    nameIdentifierScheme: ").append(toIndentedString(nameIdentifierScheme)).append("\n");
    sb.append("    schemeUri: ").append(toIndentedString(schemeUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("nameIdentifier");
    openapiFields.add("nameIdentifierScheme");
    openapiFields.add("schemeUri");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner is not found in the empty JSON string", DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("nameIdentifier") != null && !jsonObj.get("nameIdentifier").isJsonNull()) && !jsonObj.get("nameIdentifier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nameIdentifier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nameIdentifier").toString()));
      }
      if ((jsonObj.get("nameIdentifierScheme") != null && !jsonObj.get("nameIdentifierScheme").isJsonNull()) && !jsonObj.get("nameIdentifierScheme").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nameIdentifierScheme` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nameIdentifierScheme").toString()));
      }
      if ((jsonObj.get("schemeUri") != null && !jsonObj.get("schemeUri").isJsonNull()) && !jsonObj.get("schemeUri").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `schemeUri` to be a primitive type in the JSON string but got `%s`", jsonObj.get("schemeUri").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner.class));

       return (TypeAdapter<T>) new TypeAdapter<DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner>() {
           @Override
           public void write(JsonWriter out, DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner
  * @throws IOException if the JSON string is invalid with respect to DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner
  */
  public static DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner.class);
  }

 /**
  * Convert an instance of DoiPropertiesMetadataCreatorsInnerNameIdentifiersInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

